openapi: 3.0.3
info:
  title: Exchange Rate API
  version: "2.0.0"
  description: |
    환율 데이터 관리 및 조회 API 서비스입니다.
    
    주요 기능:
    - 외부 환율 API 데이터 수집 및 저장
    - 영업일 기준 환율 데이터 조회
    - 웹/챗봇 형식별 데이터 제공
  contact:
    name: API Support
    email: admin@company.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3009
    description: Development server
  - url: http://aipc.sec.samsung.net/api/exchange
    description: Production server

tags:
  - name: exchange
    description: 환율 데이터 관리
  - name: system
    description: 시스템 관리

paths:
  /exchange_api2db:
    get:
      tags:
        - exchange
      summary: 환율 데이터 수집 및 저장
      description: |
        한국수출입은행 API에서 환율 데이터를 가져와 데이터베이스에 저장합니다.
        3단계 진행 상황이 실시간으로 표시됩니다.
      operationId: collectExchangeRates
      responses:
        '200':
          description: 환율 데이터 수집 및 저장 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "환율 데이터가 성공적으로 저장되었습니다"
                  data:
                    type: object
                    properties:
                      records_saved:
                        type: integer
                        example: 42
                      last_updated:
                        type: string
                        format: date-time
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /exchange_db2api:
    get:
      tags:
        - exchange
      summary: 환율 데이터 조회
      description: |
        데이터베이스에서 환율 데이터를 조회합니다.
        영업일 기준으로 최근 데이터를 반환하며, 웹/챗봇 형식을 지원합니다.
      operationId: getExchangeRates
      parameters:
        - name: days
          in: query
          required: true
          description: 조회할 일수 (영업일 기준)
          schema:
            type: integer
            minimum: 1
            maximum: 30
            example: 7
        - name: format
          in: query
          required: true
          description: 응답 데이터 형식
          schema:
            type: string
            enum: [web, chat]
            example: web
      responses:
        '200':
          description: 환율 데이터 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ExchangeRate'
                  meta:
                    type: object
                    properties:
                      total_records:
                        type: integer
                      business_days:
                        type: integer
                      format:
                        type: string
        '400':
          description: 잘못된 요청 파라미터
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: 해당 기간의 데이터가 없음
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /health:
    get:
      tags:
        - system
      summary: 서비스 상태 확인
      description: |
        API 서비스와 PostgREST 연결 상태를 확인합니다.
        환율 테이블의 데이터 요약 정보도 함께 제공됩니다.
      operationId: healthCheck
      responses:
        '200':
          description: 서비스 정상 상태
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  service:
                    type: string
                    example: "Exchange Rate API"
                  version:
                    type: string
                    example: "2.0.0"
                  timestamp:
                    type: string
                    format: date-time
                  database:
                    type: object
                    properties:
                      status:
                        type: string
                        example: "connected"
                      last_update:
                        type: string
                        format: date-time
                      total_records:
                        type: integer
        '500':
          description: 서비스 오류 또는 연결 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    ExchangeRate:
      type: object
      properties:
        currency_code:
          type: string
          description: 통화 코드 (ISO 4217)
          example: "USD"
        currency_name:
          type: string
          description: 통화명
          example: "미국 달러"
        exchange_rate:
          type: number
          format: float
          description: 환율 (원화 기준)
          example: 1327.50
        rate_date:
          type: string
          format: date
          description: 환율 기준일
          example: "2024-01-15"
        rate_type:
          type: string
          description: 환율 유형
          enum: ["현찰매입", "현찰매도", "송금받을때", "송금보낼때"]
          example: "송금받을때"
    
    Error:
      type: object
      properties:
        status:
          type: string
          example: "error"
        message:
          type: string
          example: "요청 처리 중 오류가 발생했습니다"
        code:
          type: integer
          example: 500
        timestamp:
          type: string
          format: date-time